server:
  port: 8082

spring:
  application:
    name: parking-service  
  data:
    mongodb:
      uri: mongodb://mongo:27017/parkingdb  

  kafka:
    bootstrap-servers: kafka:9092 
    consumer:
      group-id: parking-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer